### ISSUE TITLE
Support for Elgato Light Stripes

### ISSUE THREAD

**Issue by sebinside** [NickParks/elgato-light-api#2]
Elgato recently released [Light Stripes](https://www.elgato.com/en/light-strip) which can also be controlled using the well known interface, e.g., with the following data

```
{
    "numberOfLights": 1,
    "lights": [
        {
            "on": 1,
            "hue": 200.0,
            "saturation": 100.0,
            "brightness": 82.0,
            "temperature": 0
        }
    ]
}
```

where hue is a number between [0,360), saturation is a number between [0,100] and brightness is a number between [0,100]. At least in my testing, temperature remains always 0.

It would be great to have support for these using your library, too!

**Comment by NickParks** [comment]
Hi there-- If anyone wants to make a pull request (or honestly create their own fork of the project to update it) that would probably be the best option.

I don't currently have access to Elgato Light Strips, and probably won't for some time. So testing these/verifying they work will be difficult for me atm.

**Comment by DavidCraftDev** [comment]
Why don't you create a pull request and just add it to this library
